services:
  web:
    image: geneirodan/decision-mate:dev
#    build:
#      context: src
#      dockerfile: Web/Dockerfile
    ports:
      - "23451:8080"
    environment:
      - ConnectionStrings__Postgres=Host=host.docker.internal;Port=5432;Database=decision_mate_db;UserName=postgres;Password=postgres
      - ConnectionStrings__Redis=host.docker.internal:6379