<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Geneirodan.Abstractions" />
    <PackageReference Include="MediatR.Contracts" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Common\Resources\ErrorMessages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
