<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client"/>
    <PackageReference Include="Testcontainers.Keycloak"/>
    <PackageReference Include="Testcontainers.PostgreSql"/>
    <PackageReference Include="Testcontainers.Redis"/>
    <PackageReference Include="Testcontainers.XunitV3"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Web\Web.csproj"/>
  </ItemGroup>
</Project>
