// <auto-generated />
using System;
using DecisionMate.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DecisionMate.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("DecisionMate.Domain.DecisionGames.DecisionGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("code");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("settings");

                    b.HasKey("Id")
                        .HasName("pk_decision_games");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_decision_games_category_id");

                    b.ToTable("decision_games", (string)null);
                });

            modelBuilder.Entity("DecisionMate.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("UserProfileUserProfile", b =>
                {
                    b.Property<Guid>("UserProfile1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile1id");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("UserProfile1Id", "UserProfileId")
                        .HasName("pk_friends");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("ix_friends_user_profile_id");

                    b.ToTable("friends", (string)null);
                });

            modelBuilder.Entity("DecisionMate.Domain.Categories.Category", b =>
                {
                    b.OwnsMany("DecisionMate.Domain.Categories.Options.Option", "Options", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid")
                                .HasColumnName("category_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("description");

                            b1.Property<string>("ImageUrl")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("image_url");

                            b1.Property<string>("Metadata")
                                .HasColumnType("text")
                                .HasColumnName("metadata");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");

                            b1.HasKey("CategoryId", "Id")
                                .HasName("pk_options");

                            b1.ToTable("options", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CategoryId")
                                .HasConstraintName("fk_options_categories_category_id");
                        });

                    b.Navigation("Options");
                });

            modelBuilder.Entity("DecisionMate.Domain.DecisionGames.DecisionGame", b =>
                {
                    b.HasOne("DecisionMate.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_decision_games_categories_category_id");

                    b.OwnsMany("DecisionMate.Domain.DecisionGames.DecisionGame+Player", "Players", b1 =>
                        {
                            b1.Property<Guid>("DecisionGameId")
                                .HasColumnType("uuid")
                                .HasColumnName("decision_game_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Choices")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("choices");

                            b1.HasKey("DecisionGameId", "Id")
                                .HasName("pk_players");

                            b1.HasIndex("Id")
                                .IsUnique()
                                .HasDatabaseName("ix_players_id");

                            b1.ToTable("players", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DecisionGameId")
                                .HasConstraintName("fk_players_decision_games_decision_game_id");

                            b1.HasOne("DecisionMate.Domain.Users.UserProfile", null)
                                .WithOne()
                                .HasForeignKey("DecisionMate.Domain.DecisionGames.DecisionGame.Players#DecisionMate.Domain.DecisionGames.DecisionGame+Player", "Id")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_players_user_profile_id");
                        });

                    b.OwnsMany("DecisionMate.Domain.DecisionGames.ValueObjects.DecisionResult", "Results", b1 =>
                        {
                            b1.Property<Guid>("DecisionGameId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Option")
                                .HasColumnType("integer");

                            b1.Property<int>("Points")
                                .HasColumnType("integer");

                            b1.HasKey("DecisionGameId", "__synthesizedOrdinal");

                            b1.ToTable("decision_games");

                            b1.ToJson("results");

                            b1.WithOwner()
                                .HasForeignKey("DecisionGameId")
                                .HasConstraintName("fk_decision_games_decision_games_decision_game_id");
                        });

                    b.Navigation("Players");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("UserProfileUserProfile", b =>
                {
                    b.HasOne("DecisionMate.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfile1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friends_profiles_user_profile1id");

                    b.HasOne("DecisionMate.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friends_profiles_user_profile_id");
                });
#pragma warning restore 612, 618
        }
    }
}
