<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Geneirodan.MediatR" />
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Riok.Mapperly" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Common\Resources\ErrorMessages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Common\Resources\Messages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Messages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Common\Resources\ErrorMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
