<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Dapper.EntityFramework" Version="2.1.66" />
    <PackageVersion Include="EFCore.NamingConventions" Version="9.0.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageVersion Include="Geneirodan.Abstractions" Version="1.0.4" />
    <PackageVersion Include="Geneirodan.AspNetCore" Version="1.0.4" />
    <PackageVersion Include="Geneirodan.EntityFrameworkCore" Version="1.0.4" />
    <PackageVersion Include="Geneirodan.MediatR" Version="1.0.4" />
    <PackageVersion Include="geneirodan.observability" Version="1.0.4" />
    <PackageVersion Include="JetBrains.Annotations" Version="2024.3.0" />
    <PackageVersion Include="MediatR.Contracts" Version="2.0.1" />
    <PackageVersion Include="Meziantou.Analyzer" Version="2.0.201">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.6" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Hybrid" Version="9.6.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.6" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="9.0.6" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="9.0.6" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageVersion Include="Riok.Mapperly" Version="4.2.1" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.4.14" />
    <PackageVersion Include="Scrutor" Version="6.1.0" />
    <PackageVersion Include="TypedSignalR.Client.DevTools" Version="1.2.4" />
  </ItemGroup>
</Project>