<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DecisionMate.$(MSBuildProjectName)</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Meziantou.Analyzer"/>
  </ItemGroup>
</Project>
